#!/usr/bin/env bash
# write a Bash script that configures a new Ubuntu machine nginx
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
