#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo sed -i '/server_name _;/a \location /redirect_me {\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}' /etc/nginx/sites-available/default
# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \error_page 404 /404.html;\n location = /404.html {\n internal;\n}' /etc/nginx/sites-available/default
sudo service nginx restart
