#!/usr/bin/env bash
# This script configures Nginx so that its HTTP response

apt-get -y update
apt-get -y install nginx

service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html

# create a redirection for our website
sudo sed -i '/server_name _;/a \	location /redirect_me {\n		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n	}' /etc/nginx/sites-available/default


# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \        error_page 404 /404.html;\n        location = /404.html {\n                internal;\n        }' /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/ a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

service nginx restart
