#!/usr/bin/env bash
# Install and configure HAproxy on my load balancer

sudo apt-get update
sudo apt-get install haproxy -y

# Configure loadbalancer
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend Chinenye-frontend
        bind *:80
        mode http
        default_backend Chinenye-backend

backend Chinenye-backend
        balance roundrobin
        server 301925-web-01 34.229.66.208:80 check
        server 301925-web-02 100.24.255.208:80 check
EOT
# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
