#!/usr/bin/env bash
# fix nginx web server and start listening on port 80 by creating a symbolic link

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
