#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

i=0
while ((i <= 12))
do
echo "Hour: $i"
j=1
while ((j <= 59))
do
echo "$j"
((j++))
done
((i++))
done
